# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.7
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_lathe', [dirname(__file__)])
        except ImportError:
            import _lathe
            return _lathe
        if fp is not None:
            try:
                _mod = imp.load_module('_lathe', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _lathe = swig_import_helper()
    del swig_import_helper
else:
    import _lathe
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



_lathe.INCLUDE_swigconstant(_lathe)
INCLUDE = _lathe.INCLUDE

_lathe.DBG_P_swigconstant(_lathe)
DBG_P = _lathe.DBG_P

_lathe.DBG_SETUP_swigconstant(_lathe)
DBG_SETUP = _lathe.DBG_SETUP

_lathe.DBG_DETAIL_swigconstant(_lathe)
DBG_DETAIL = _lathe.DBG_DETAIL

_lathe.JTIMEINITIAL_swigconstant(_lathe)
JTIMEINITIAL = _lathe.JTIMEINITIAL

_lathe.JTIMEINC_swigconstant(_lathe)
JTIMEINC = _lathe.JTIMEINC

_lathe.JTIMEMAX_swigconstant(_lathe)
JTIMEMAX = _lathe.JTIMEMAX
class T_AXIS(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, T_AXIS, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, T_AXIS, name)
    __repr__ = _swig_repr
    __swig_setmethods__["pitch"] = _lathe.T_AXIS_pitch_set
    __swig_getmethods__["pitch"] = _lathe.T_AXIS_pitch_get
    if _newclass:
        pitch = _swig_property(_lathe.T_AXIS_pitch_get, _lathe.T_AXIS_pitch_set)
    __swig_setmethods__["ratio"] = _lathe.T_AXIS_ratio_set
    __swig_getmethods__["ratio"] = _lathe.T_AXIS_ratio_get
    if _newclass:
        ratio = _swig_property(_lathe.T_AXIS_ratio_get, _lathe.T_AXIS_ratio_set)
    __swig_setmethods__["microSteps"] = _lathe.T_AXIS_microSteps_set
    __swig_getmethods__["microSteps"] = _lathe.T_AXIS_microSteps_get
    if _newclass:
        microSteps = _swig_property(_lathe.T_AXIS_microSteps_get, _lathe.T_AXIS_microSteps_set)
    __swig_setmethods__["motorSteps"] = _lathe.T_AXIS_motorSteps_set
    __swig_getmethods__["motorSteps"] = _lathe.T_AXIS_motorSteps_get
    if _newclass:
        motorSteps = _swig_property(_lathe.T_AXIS_motorSteps_get, _lathe.T_AXIS_motorSteps_set)
    __swig_setmethods__["accel"] = _lathe.T_AXIS_accel_set
    __swig_getmethods__["accel"] = _lathe.T_AXIS_accel_get
    if _newclass:
        accel = _swig_property(_lathe.T_AXIS_accel_get, _lathe.T_AXIS_accel_set)
    __swig_setmethods__["backlash"] = _lathe.T_AXIS_backlash_set
    __swig_getmethods__["backlash"] = _lathe.T_AXIS_backlash_get
    if _newclass:
        backlash = _swig_property(_lathe.T_AXIS_backlash_get, _lathe.T_AXIS_backlash_set)
    __swig_setmethods__["stepsInch"] = _lathe.T_AXIS_stepsInch_set
    __swig_getmethods__["stepsInch"] = _lathe.T_AXIS_stepsInch_get
    if _newclass:
        stepsInch = _swig_property(_lathe.T_AXIS_stepsInch_get, _lathe.T_AXIS_stepsInch_set)
    __swig_setmethods__["backlashSteps"] = _lathe.T_AXIS_backlashSteps_set
    __swig_getmethods__["backlashSteps"] = _lathe.T_AXIS_backlashSteps_get
    if _newclass:
        backlashSteps = _swig_property(_lathe.T_AXIS_backlashSteps_get, _lathe.T_AXIS_backlashSteps_set)

    def __init__(self):
        this = _lathe.new_T_AXIS()
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _lathe.delete_T_AXIS
    __del__ = lambda self: None
T_AXIS_swigregister = _lathe.T_AXIS_swigregister
T_AXIS_swigregister(T_AXIS)

class T_ACCEL(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, T_ACCEL, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, T_ACCEL, name)
    __repr__ = _swig_repr
    __swig_setmethods__["minFeed"] = _lathe.T_ACCEL_minFeed_set
    __swig_getmethods__["minFeed"] = _lathe.T_ACCEL_minFeed_get
    if _newclass:
        minFeed = _swig_property(_lathe.T_ACCEL_minFeed_get, _lathe.T_ACCEL_minFeed_set)
    __swig_setmethods__["maxFeed"] = _lathe.T_ACCEL_maxFeed_set
    __swig_getmethods__["maxFeed"] = _lathe.T_ACCEL_maxFeed_get
    if _newclass:
        maxFeed = _swig_property(_lathe.T_ACCEL_maxFeed_get, _lathe.T_ACCEL_maxFeed_set)
    __swig_setmethods__["accel"] = _lathe.T_ACCEL_accel_set
    __swig_getmethods__["accel"] = _lathe.T_ACCEL_accel_get
    if _newclass:
        accel = _swig_property(_lathe.T_ACCEL_accel_get, _lathe.T_ACCEL_accel_set)
    __swig_setmethods__["pitch"] = _lathe.T_ACCEL_pitch_set
    __swig_getmethods__["pitch"] = _lathe.T_ACCEL_pitch_get
    if _newclass:
        pitch = _swig_property(_lathe.T_ACCEL_pitch_get, _lathe.T_ACCEL_pitch_set)
    __swig_setmethods__["stepsInch"] = _lathe.T_ACCEL_stepsInch_set
    __swig_getmethods__["stepsInch"] = _lathe.T_ACCEL_stepsInch_get
    if _newclass:
        stepsInch = _swig_property(_lathe.T_ACCEL_stepsInch_get, _lathe.T_ACCEL_stepsInch_set)
    __swig_setmethods__["taper"] = _lathe.T_ACCEL_taper_set
    __swig_getmethods__["taper"] = _lathe.T_ACCEL_taper_get
    if _newclass:
        taper = _swig_property(_lathe.T_ACCEL_taper_get, _lathe.T_ACCEL_taper_set)
    __swig_setmethods__["taperInch"] = _lathe.T_ACCEL_taperInch_set
    __swig_getmethods__["taperInch"] = _lathe.T_ACCEL_taperInch_get
    if _newclass:
        taperInch = _swig_property(_lathe.T_ACCEL_taperInch_get, _lathe.T_ACCEL_taperInch_set)
    __swig_setmethods__["clockFreq"] = _lathe.T_ACCEL_clockFreq_set
    __swig_getmethods__["clockFreq"] = _lathe.T_ACCEL_clockFreq_get
    if _newclass:
        clockFreq = _swig_property(_lathe.T_ACCEL_clockFreq_get, _lathe.T_ACCEL_clockFreq_set)
    __swig_setmethods__["clocksPerInch"] = _lathe.T_ACCEL_clocksPerInch_set
    __swig_getmethods__["clocksPerInch"] = _lathe.T_ACCEL_clocksPerInch_get
    if _newclass:
        clocksPerInch = _swig_property(_lathe.T_ACCEL_clocksPerInch_get, _lathe.T_ACCEL_clocksPerInch_set)
    __swig_setmethods__["accelTime"] = _lathe.T_ACCEL_accelTime_set
    __swig_getmethods__["accelTime"] = _lathe.T_ACCEL_accelTime_get
    if _newclass:
        accelTime = _swig_property(_lathe.T_ACCEL_accelTime_get, _lathe.T_ACCEL_accelTime_set)
    __swig_setmethods__["accelSteps"] = _lathe.T_ACCEL_accelSteps_set
    __swig_getmethods__["accelSteps"] = _lathe.T_ACCEL_accelSteps_get
    if _newclass:
        accelSteps = _swig_property(_lathe.T_ACCEL_accelSteps_get, _lathe.T_ACCEL_accelSteps_set)
    __swig_setmethods__["steps"] = _lathe.T_ACCEL_steps_set
    __swig_getmethods__["steps"] = _lathe.T_ACCEL_steps_get
    if _newclass:
        steps = _swig_property(_lathe.T_ACCEL_steps_get, _lathe.T_ACCEL_steps_set)
    __swig_setmethods__["stepsSec"] = _lathe.T_ACCEL_stepsSec_set
    __swig_getmethods__["stepsSec"] = _lathe.T_ACCEL_stepsSec_get
    if _newclass:
        stepsSec = _swig_property(_lathe.T_ACCEL_stepsSec_get, _lathe.T_ACCEL_stepsSec_set)
    __swig_setmethods__["time"] = _lathe.T_ACCEL_time_set
    __swig_getmethods__["time"] = _lathe.T_ACCEL_time_get
    if _newclass:
        time = _swig_property(_lathe.T_ACCEL_time_get, _lathe.T_ACCEL_time_set)
    __swig_setmethods__["scale"] = _lathe.T_ACCEL_scale_set
    __swig_getmethods__["scale"] = _lathe.T_ACCEL_scale_get
    if _newclass:
        scale = _swig_property(_lathe.T_ACCEL_scale_get, _lathe.T_ACCEL_scale_set)
    __swig_setmethods__["dx"] = _lathe.T_ACCEL_dx_set
    __swig_getmethods__["dx"] = _lathe.T_ACCEL_dx_get
    if _newclass:
        dx = _swig_property(_lathe.T_ACCEL_dx_get, _lathe.T_ACCEL_dx_set)
    __swig_setmethods__["dyIni"] = _lathe.T_ACCEL_dyIni_set
    __swig_getmethods__["dyIni"] = _lathe.T_ACCEL_dyIni_get
    if _newclass:
        dyIni = _swig_property(_lathe.T_ACCEL_dyIni_get, _lathe.T_ACCEL_dyIni_set)
    __swig_setmethods__["dyMax"] = _lathe.T_ACCEL_dyMax_set
    __swig_getmethods__["dyMax"] = _lathe.T_ACCEL_dyMax_get
    if _newclass:
        dyMax = _swig_property(_lathe.T_ACCEL_dyMax_get, _lathe.T_ACCEL_dyMax_set)
    __swig_setmethods__["intIncPerClock"] = _lathe.T_ACCEL_intIncPerClock_set
    __swig_getmethods__["intIncPerClock"] = _lathe.T_ACCEL_intIncPerClock_get
    if _newclass:
        intIncPerClock = _swig_property(_lathe.T_ACCEL_intIncPerClock_get, _lathe.T_ACCEL_intIncPerClock_set)
    __swig_setmethods__["sum"] = _lathe.T_ACCEL_sum_set
    __swig_getmethods__["sum"] = _lathe.T_ACCEL_sum_get
    if _newclass:
        sum = _swig_property(_lathe.T_ACCEL_sum_get, _lathe.T_ACCEL_sum_set)
    __swig_setmethods__["incr1"] = _lathe.T_ACCEL_incr1_set
    __swig_getmethods__["incr1"] = _lathe.T_ACCEL_incr1_get
    if _newclass:
        incr1 = _swig_property(_lathe.T_ACCEL_incr1_get, _lathe.T_ACCEL_incr1_set)
    __swig_setmethods__["incr2"] = _lathe.T_ACCEL_incr2_set
    __swig_getmethods__["incr2"] = _lathe.T_ACCEL_incr2_get
    if _newclass:
        incr2 = _swig_property(_lathe.T_ACCEL_incr2_get, _lathe.T_ACCEL_incr2_set)
    __swig_setmethods__["intAccel"] = _lathe.T_ACCEL_intAccel_set
    __swig_getmethods__["intAccel"] = _lathe.T_ACCEL_intAccel_get
    if _newclass:
        intAccel = _swig_property(_lathe.T_ACCEL_intAccel_get, _lathe.T_ACCEL_intAccel_set)
    __swig_setmethods__["accelClocks"] = _lathe.T_ACCEL_accelClocks_set
    __swig_getmethods__["accelClocks"] = _lathe.T_ACCEL_accelClocks_get
    if _newclass:
        accelClocks = _swig_property(_lathe.T_ACCEL_accelClocks_get, _lathe.T_ACCEL_accelClocks_set)
    __swig_setmethods__["freqDivider"] = _lathe.T_ACCEL_freqDivider_set
    __swig_getmethods__["freqDivider"] = _lathe.T_ACCEL_freqDivider_get
    if _newclass:
        freqDivider = _swig_property(_lathe.T_ACCEL_freqDivider_get, _lathe.T_ACCEL_freqDivider_set)

    def __init__(self):
        this = _lathe.new_T_ACCEL()
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _lathe.delete_T_ACCEL
    __del__ = lambda self: None
T_ACCEL_swigregister = _lathe.T_ACCEL_swigregister
T_ACCEL_swigregister(T_ACCEL)

class T_MOVECTL(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, T_MOVECTL, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, T_MOVECTL, name)
    __repr__ = _swig_repr
    __swig_setmethods__["state"] = _lathe.T_MOVECTL_state_set
    __swig_getmethods__["state"] = _lathe.T_MOVECTL_state_get
    if _newclass:
        state = _swig_property(_lathe.T_MOVECTL_state_get, _lathe.T_MOVECTL_state_set)
    __swig_setmethods__["prev"] = _lathe.T_MOVECTL_prev_set
    __swig_getmethods__["prev"] = _lathe.T_MOVECTL_prev_get
    if _newclass:
        prev = _swig_property(_lathe.T_MOVECTL_prev_get, _lathe.T_MOVECTL_prev_set)
    __swig_setmethods__["cmd"] = _lathe.T_MOVECTL_cmd_set
    __swig_getmethods__["cmd"] = _lathe.T_MOVECTL_cmd_get
    if _newclass:
        cmd = _swig_property(_lathe.T_MOVECTL_cmd_get, _lathe.T_MOVECTL_cmd_set)
    __swig_setmethods__["stop"] = _lathe.T_MOVECTL_stop_set
    __swig_getmethods__["stop"] = _lathe.T_MOVECTL_stop_get
    if _newclass:
        stop = _swig_property(_lathe.T_MOVECTL_stop_get, _lathe.T_MOVECTL_stop_set)
    __swig_setmethods__["done"] = _lathe.T_MOVECTL_done_set
    __swig_getmethods__["done"] = _lathe.T_MOVECTL_done_get
    if _newclass:
        done = _swig_property(_lathe.T_MOVECTL_done_get, _lathe.T_MOVECTL_done_set)
    __swig_setmethods__["ctlreg"] = _lathe.T_MOVECTL_ctlreg_set
    __swig_getmethods__["ctlreg"] = _lathe.T_MOVECTL_ctlreg_get
    if _newclass:
        ctlreg = _swig_property(_lathe.T_MOVECTL_ctlreg_get, _lathe.T_MOVECTL_ctlreg_set)
    __swig_setmethods__["dir"] = _lathe.T_MOVECTL_dir_set
    __swig_getmethods__["dir"] = _lathe.T_MOVECTL_dir_get
    if _newclass:
        dir = _swig_property(_lathe.T_MOVECTL_dir_get, _lathe.T_MOVECTL_dir_set)
    __swig_setmethods__["dirChange"] = _lathe.T_MOVECTL_dirChange_set
    __swig_getmethods__["dirChange"] = _lathe.T_MOVECTL_dirChange_get
    if _newclass:
        dirChange = _swig_property(_lathe.T_MOVECTL_dirChange_get, _lathe.T_MOVECTL_dirChange_set)
    __swig_setmethods__["dist"] = _lathe.T_MOVECTL_dist_set
    __swig_getmethods__["dist"] = _lathe.T_MOVECTL_dist_get
    if _newclass:
        dist = _swig_property(_lathe.T_MOVECTL_dist_get, _lathe.T_MOVECTL_dist_set)
    __swig_setmethods__["loc"] = _lathe.T_MOVECTL_loc_set
    __swig_getmethods__["loc"] = _lathe.T_MOVECTL_loc_get
    if _newclass:
        loc = _swig_property(_lathe.T_MOVECTL_loc_get, _lathe.T_MOVECTL_loc_set)
    __swig_setmethods__["iniDist"] = _lathe.T_MOVECTL_iniDist_set
    __swig_getmethods__["iniDist"] = _lathe.T_MOVECTL_iniDist_get
    if _newclass:
        iniDist = _swig_property(_lathe.T_MOVECTL_iniDist_get, _lathe.T_MOVECTL_iniDist_set)
    __swig_setmethods__["maxDist"] = _lathe.T_MOVECTL_maxDist_set
    __swig_getmethods__["maxDist"] = _lathe.T_MOVECTL_maxDist_get
    if _newclass:
        maxDist = _swig_property(_lathe.T_MOVECTL_maxDist_get, _lathe.T_MOVECTL_maxDist_set)
    __swig_setmethods__["jogInc"] = _lathe.T_MOVECTL_jogInc_set
    __swig_getmethods__["jogInc"] = _lathe.T_MOVECTL_jogInc_get
    if _newclass:
        jogInc = _swig_property(_lathe.T_MOVECTL_jogInc_get, _lathe.T_MOVECTL_jogInc_set)

    def __init__(self):
        this = _lathe.new_T_MOVECTL()
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _lathe.delete_T_MOVECTL
    __del__ = lambda self: None
T_MOVECTL_swigregister = _lathe.T_MOVECTL_swigregister
T_MOVECTL_swigregister(T_MOVECTL)
cvar = _lathe.cvar


def pauseCmd():
    return _lathe.pauseCmd()
pauseCmd = _lathe.pauseCmd

def resumeCmd():
    return _lathe.resumeCmd()
resumeCmd = _lathe.resumeCmd

def stopCmd():
    return _lathe.stopCmd()
stopCmd = _lathe.stopCmd

def clearCmd():
    return _lathe.clearCmd()
clearCmd = _lathe.clearCmd

def allStop():
    return _lathe.allStop()
allStop = _lathe.allStop

def clearAll():
    return _lathe.clearAll()
clearAll = _lathe.clearAll

def setup():
    return _lathe.setup()
setup = _lathe.setup

def spindleStart():
    return _lathe.spindleStart()
spindleStart = _lathe.spindleStart

def spindleStop():
    return _lathe.spindleStop()
spindleStop = _lathe.spindleStop

def spindleSetup():
    return _lathe.spindleSetup()
spindleSetup = _lathe.spindleSetup

def zMoveCmd():
    return _lathe.zMoveCmd()
zMoveCmd = _lathe.zMoveCmd

def zJogCmd():
    return _lathe.zJogCmd()
zJogCmd = _lathe.zJogCmd

def zHomeCmd():
    return _lathe.zHomeCmd()
zHomeCmd = _lathe.zHomeCmd

def zLocCmd():
    return _lathe.zLocCmd()
zLocCmd = _lathe.zLocCmd

def zGoHomeCmd():
    return _lathe.zGoHomeCmd()
zGoHomeCmd = _lathe.zGoHomeCmd

def zStop():
    return _lathe.zStop()
zStop = _lathe.zStop

def zSetup():
    return _lathe.zSetup()
zSetup = _lathe.zSetup

def zMoveSetup():
    return _lathe.zMoveSetup()
zMoveSetup = _lathe.zMoveSetup

def zSynSetup():
    return _lathe.zSynSetup()
zSynSetup = _lathe.zSynSetup

def zTaperSetup():
    return _lathe.zTaperSetup()
zTaperSetup = _lathe.zTaperSetup

def xMoveCmd():
    return _lathe.xMoveCmd()
xMoveCmd = _lathe.xMoveCmd

def xJogCmd():
    return _lathe.xJogCmd()
xJogCmd = _lathe.xJogCmd

def xHomeCmd():
    return _lathe.xHomeCmd()
xHomeCmd = _lathe.xHomeCmd

def xLocCmd():
    return _lathe.xLocCmd()
xLocCmd = _lathe.xLocCmd

def xGoHomeCmd():
    return _lathe.xGoHomeCmd()
xGoHomeCmd = _lathe.xGoHomeCmd

def xStop():
    return _lathe.xStop()
xStop = _lathe.xStop

def xSetup():
    return _lathe.xSetup()
xSetup = _lathe.xSetup

def xMoveSetup():
    return _lathe.xMoveSetup()
xMoveSetup = _lathe.xMoveSetup

def xSynSetup():
    return _lathe.xSynSetup()
xSynSetup = _lathe.xSynSetup

def xTaperSetup():
    return _lathe.xTaperSetup()
xTaperSetup = _lathe.xTaperSetup

def accelCalc(ac):
    return _lathe.accelCalc(ac)
accelCalc = _lathe.accelCalc

def turnPitch(ac, pitch):
    return _lathe.turnPitch(ac, pitch)
turnPitch = _lathe.turnPitch

def threadTPI(ac, tpi):
    return _lathe.threadTPI(ac, tpi)
threadTPI = _lathe.threadTPI

def threadMetric(ac, pitch):
    return _lathe.threadMetric(ac, pitch)
threadMetric = _lathe.threadMetric

def turnAccel(ac, accel):
    return _lathe.turnAccel(ac, accel)
turnAccel = _lathe.turnAccel

def accelSetup(ac):
    return _lathe.accelSetup(ac)
accelSetup = _lathe.accelSetup

def taperCalc(a0, a1, taper):
    return _lathe.taperCalc(a0, a1, taper)
taperCalc = _lathe.taperCalc

def zTaperInit(ac, dir):
    return _lathe.zTaperInit(ac, dir)
zTaperInit = _lathe.zTaperInit

def xTaperInit(ac, dir):
    return _lathe.xTaperInit(ac, dir)
xTaperInit = _lathe.xTaperInit

def i64toa(val, buf, buflen):
    return _lathe.i64toa(val, buf, buflen)
i64toa = _lathe.i64toa

def tmp(x):
    return _lathe.tmp(x)
tmp = _lathe.tmp
# This file is compatible with both classic and new-style classes.


