# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.7
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info

if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_remcmd', [dirname(__file__)])
        except ImportError:
            import _remcmd
            return _remcmd
        if fp is not None:
            try:
                _mod = imp.load_module('_remcmd', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _remcmd = swig_import_helper()
    del swig_import_helper
else:
    import _remcmd
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



_remcmd.ZMOVE_swigconstant(_remcmd)
ZMOVE = _remcmd.ZMOVE

_remcmd.ZSTOP_swigconstant(_remcmd)
ZSTOP = _remcmd.ZSTOP

_remcmd.ZHOME_swigconstant(_remcmd)
ZHOME = _remcmd.ZHOME

_remcmd.ZSETLOC_swigconstant(_remcmd)
ZSETLOC = _remcmd.ZSETLOC

_remcmd.ZGOHOME_swigconstant(_remcmd)
ZGOHOME = _remcmd.ZGOHOME

_remcmd.XMOVE_swigconstant(_remcmd)
XMOVE = _remcmd.XMOVE

_remcmd.XSTOP_swigconstant(_remcmd)
XSTOP = _remcmd.XSTOP

_remcmd.XHOME_swigconstant(_remcmd)
XHOME = _remcmd.XHOME

_remcmd.XSETLOC_swigconstant(_remcmd)
XSETLOC = _remcmd.XSETLOC

_remcmd.XGOHOME_swigconstant(_remcmd)
XGOHOME = _remcmd.XGOHOME

_remcmd.SPINDLE_START_swigconstant(_remcmd)
SPINDLE_START = _remcmd.SPINDLE_START

_remcmd.SPINDLE_STOP_swigconstant(_remcmd)
SPINDLE_STOP = _remcmd.SPINDLE_STOP

_remcmd.CMD_PAUSE_swigconstant(_remcmd)
CMD_PAUSE = _remcmd.CMD_PAUSE

_remcmd.CMD_RESUME_swigconstant(_remcmd)
CMD_RESUME = _remcmd.CMD_RESUME

_remcmd.CMD_STOP_swigconstant(_remcmd)
CMD_STOP = _remcmd.CMD_STOP

_remcmd.CMD_CLEAR_swigconstant(_remcmd)
CMD_CLEAR = _remcmd.CMD_CLEAR

_remcmd.CMD_SETUP_swigconstant(_remcmd)
CMD_SETUP = _remcmd.CMD_SETUP

_remcmd.CMD_SPSETUP_swigconstant(_remcmd)
CMD_SPSETUP = _remcmd.CMD_SPSETUP

_remcmd.CMD_ZSETUP_swigconstant(_remcmd)
CMD_ZSETUP = _remcmd.CMD_ZSETUP

_remcmd.CMD_ZSYNSETUP_swigconstant(_remcmd)
CMD_ZSYNSETUP = _remcmd.CMD_ZSYNSETUP

_remcmd.CMD_ZTAPERSETUP_swigconstant(_remcmd)
CMD_ZTAPERSETUP = _remcmd.CMD_ZTAPERSETUP

_remcmd.CMD_XSETUP_swigconstant(_remcmd)
CMD_XSETUP = _remcmd.CMD_XSETUP

_remcmd.CMD_XSYNSETUP_swigconstant(_remcmd)
CMD_XSYNSETUP = _remcmd.CMD_XSYNSETUP

_remcmd.CMD_XTAPERSETUP_swigconstant(_remcmd)
CMD_XTAPERSETUP = _remcmd.CMD_XTAPERSETUP

_remcmd.READSTAT_swigconstant(_remcmd)
READSTAT = _remcmd.READSTAT

_remcmd.READISTATE_swigconstant(_remcmd)
READISTATE = _remcmd.READISTATE

_remcmd.LOADVAL_swigconstant(_remcmd)
LOADVAL = _remcmd.LOADVAL

_remcmd.READVAL_swigconstant(_remcmd)
READVAL = _remcmd.READVAL

_remcmd.LOADXREG_swigconstant(_remcmd)
LOADXREG = _remcmd.LOADXREG

_remcmd.READXREG_swigconstant(_remcmd)
READXREG = _remcmd.READXREG

_remcmd.SENDMOVE_swigconstant(_remcmd)
SENDMOVE = _remcmd.SENDMOVE

_remcmd.MOVEQUESTATUS_swigconstant(_remcmd)
MOVEQUESTATUS = _remcmd.MOVEQUESTATUS

_remcmd.READLOC_swigconstant(_remcmd)
READLOC = _remcmd.READLOC

_remcmd.READDBG_swigconstant(_remcmd)
READDBG = _remcmd.READDBG

_remcmd.LOADZPRM_swigconstant(_remcmd)
LOADZPRM = _remcmd.LOADZPRM

_remcmd.LOADXPRM_swigconstant(_remcmd)
LOADXPRM = _remcmd.LOADXPRM

_remcmd.LOADSPRM_swigconstant(_remcmd)
LOADSPRM = _remcmd.LOADSPRM

_remcmd.LOADTPRM_swigconstant(_remcmd)
LOADTPRM = _remcmd.LOADTPRM

_remcmd.PRMPHASE_swigconstant(_remcmd)
PRMPHASE = _remcmd.PRMPHASE

_remcmd.PRMSDX_swigconstant(_remcmd)
PRMSDX = _remcmd.PRMSDX

_remcmd.PRMSDYINI_swigconstant(_remcmd)
PRMSDYINI = _remcmd.PRMSDYINI

_remcmd.PRMSDY_swigconstant(_remcmd)
PRMSDY = _remcmd.PRMSDY

_remcmd.PRMSD_swigconstant(_remcmd)
PRMSD = _remcmd.PRMSD

_remcmd.PRMSINCR1_swigconstant(_remcmd)
PRMSINCR1 = _remcmd.PRMSINCR1

_remcmd.PRMSINCR2_swigconstant(_remcmd)
PRMSINCR2 = _remcmd.PRMSINCR2

_remcmd.PRMSACCEL_swigconstant(_remcmd)
PRMSACCEL = _remcmd.PRMSACCEL

_remcmd.PRMSACLCLKS_swigconstant(_remcmd)
PRMSACLCLKS = _remcmd.PRMSACLCLKS

_remcmd.PRMTDX_swigconstant(_remcmd)
PRMTDX = _remcmd.PRMTDX

_remcmd.PRMTDY_swigconstant(_remcmd)
PRMTDY = _remcmd.PRMTDY

_remcmd.PRMTD_swigconstant(_remcmd)
PRMTD = _remcmd.PRMTD

_remcmd.PRMTINCR1_swigconstant(_remcmd)
PRMTINCR1 = _remcmd.PRMTINCR1

_remcmd.PRMTINCR2_swigconstant(_remcmd)
PRMTINCR2 = _remcmd.PRMTINCR2

_remcmd.PRMZLOCIN_swigconstant(_remcmd)
PRMZLOCIN = _remcmd.PRMZLOCIN

_remcmd.PRMZDISTIN_swigconstant(_remcmd)
PRMZDISTIN = _remcmd.PRMZDISTIN

_remcmd.PRMZDIST_swigconstant(_remcmd)
PRMZDIST = _remcmd.PRMZDIST

_remcmd.PRMZLOC_swigconstant(_remcmd)
PRMZLOC = _remcmd.PRMZLOC

_remcmd.PRMZSTART_swigconstant(_remcmd)
PRMZSTART = _remcmd.PRMZSTART

_remcmd.PRMZEND_swigconstant(_remcmd)
PRMZEND = _remcmd.PRMZEND

_remcmd.PRMZCUR_swigconstant(_remcmd)
PRMZCUR = _remcmd.PRMZCUR

_remcmd.PRMZREF_swigconstant(_remcmd)
PRMZREF = _remcmd.PRMZREF

_remcmd.PRMZTOTFEED_swigconstant(_remcmd)
PRMZTOTFEED = _remcmd.PRMZTOTFEED

_remcmd.PRMZFEED_swigconstant(_remcmd)
PRMZFEED = _remcmd.PRMZFEED

_remcmd.PRMZRETRACT_swigconstant(_remcmd)
PRMZRETRACT = _remcmd.PRMZRETRACT

_remcmd.PRMZRTCLOC_swigconstant(_remcmd)
PRMZRTCLOC = _remcmd.PRMZRTCLOC

_remcmd.PRMZFREQ_swigconstant(_remcmd)
PRMZFREQ = _remcmd.PRMZFREQ

_remcmd.PRMZDX_swigconstant(_remcmd)
PRMZDX = _remcmd.PRMZDX

_remcmd.PRMZD_swigconstant(_remcmd)
PRMZD = _remcmd.PRMZD

_remcmd.PRMZINCR1_swigconstant(_remcmd)
PRMZINCR1 = _remcmd.PRMZINCR1

_remcmd.PRMZINCR2_swigconstant(_remcmd)
PRMZINCR2 = _remcmd.PRMZINCR2

_remcmd.PRMZDYINI_swigconstant(_remcmd)
PRMZDYINI = _remcmd.PRMZDYINI

_remcmd.PRMZDYJOG_swigconstant(_remcmd)
PRMZDYJOG = _remcmd.PRMZDYJOG

_remcmd.PRMZDYMAX_swigconstant(_remcmd)
PRMZDYMAX = _remcmd.PRMZDYMAX

_remcmd.PRMZACCEL_swigconstant(_remcmd)
PRMZACCEL = _remcmd.PRMZACCEL

_remcmd.PRMZACLJOG_swigconstant(_remcmd)
PRMZACLJOG = _remcmd.PRMZACLJOG

_remcmd.PRMZACLRUN_swigconstant(_remcmd)
PRMZACLRUN = _remcmd.PRMZACLRUN

_remcmd.PRMZACLMAX_swigconstant(_remcmd)
PRMZACLMAX = _remcmd.PRMZACLMAX

_remcmd.PRMZBACKLASH_swigconstant(_remcmd)
PRMZBACKLASH = _remcmd.PRMZBACKLASH

_remcmd.PRMZCTLREG_swigconstant(_remcmd)
PRMZCTLREG = _remcmd.PRMZCTLREG

_remcmd.PRMXLOCIN_swigconstant(_remcmd)
PRMXLOCIN = _remcmd.PRMXLOCIN

_remcmd.PRMXDISTIN_swigconstant(_remcmd)
PRMXDISTIN = _remcmd.PRMXDISTIN

_remcmd.PRMXDIST_swigconstant(_remcmd)
PRMXDIST = _remcmd.PRMXDIST

_remcmd.PRMXLOC_swigconstant(_remcmd)
PRMXLOC = _remcmd.PRMXLOC

_remcmd.PRMXSTART_swigconstant(_remcmd)
PRMXSTART = _remcmd.PRMXSTART

_remcmd.PRMXEND_swigconstant(_remcmd)
PRMXEND = _remcmd.PRMXEND

_remcmd.PRMXCUR_swigconstant(_remcmd)
PRMXCUR = _remcmd.PRMXCUR

_remcmd.PRMXREF_swigconstant(_remcmd)
PRMXREF = _remcmd.PRMXREF

_remcmd.PRMXTOTFEED_swigconstant(_remcmd)
PRMXTOTFEED = _remcmd.PRMXTOTFEED

_remcmd.PRMXFEED_swigconstant(_remcmd)
PRMXFEED = _remcmd.PRMXFEED

_remcmd.PRMXRETRACT_swigconstant(_remcmd)
PRMXRETRACT = _remcmd.PRMXRETRACT

_remcmd.PRMXRTCLOC_swigconstant(_remcmd)
PRMXRTCLOC = _remcmd.PRMXRTCLOC

_remcmd.PRMXFREQ_swigconstant(_remcmd)
PRMXFREQ = _remcmd.PRMXFREQ

_remcmd.PRMXDX_swigconstant(_remcmd)
PRMXDX = _remcmd.PRMXDX

_remcmd.PRMXDYINI_swigconstant(_remcmd)
PRMXDYINI = _remcmd.PRMXDYINI

_remcmd.PRMXD_swigconstant(_remcmd)
PRMXD = _remcmd.PRMXD

_remcmd.PRMXINCR1_swigconstant(_remcmd)
PRMXINCR1 = _remcmd.PRMXINCR1

_remcmd.PRMXINCR2_swigconstant(_remcmd)
PRMXINCR2 = _remcmd.PRMXINCR2

_remcmd.PRMXDYJOG_swigconstant(_remcmd)
PRMXDYJOG = _remcmd.PRMXDYJOG

_remcmd.PRMXDYMAX_swigconstant(_remcmd)
PRMXDYMAX = _remcmd.PRMXDYMAX

_remcmd.PRMXACCEL_swigconstant(_remcmd)
PRMXACCEL = _remcmd.PRMXACCEL

_remcmd.PRMXACLJOG_swigconstant(_remcmd)
PRMXACLJOG = _remcmd.PRMXACLJOG

_remcmd.PRMXACLRUN_swigconstant(_remcmd)
PRMXACLRUN = _remcmd.PRMXACLRUN

_remcmd.PRMXACLMAX_swigconstant(_remcmd)
PRMXACLMAX = _remcmd.PRMXACLMAX

_remcmd.PRMXBACKLASH_swigconstant(_remcmd)
PRMXBACKLASH = _remcmd.PRMXBACKLASH

_remcmd.PRMXCTLREG_swigconstant(_remcmd)
PRMXCTLREG = _remcmd.PRMXCTLREG

_remcmd.PRMTHTAN_swigconstant(_remcmd)
PRMTHTAN = _remcmd.PRMTHTAN

_remcmd.PRMTHFEED_swigconstant(_remcmd)
PRMTHFEED = _remcmd.PRMTHFEED

_remcmd.PRMTHZOFFSET_swigconstant(_remcmd)
PRMTHZOFFSET = _remcmd.PRMTHZOFFSET

_remcmd.PRMFEEDIDX_swigconstant(_remcmd)
PRMFEEDIDX = _remcmd.PRMFEEDIDX

_remcmd.PRMPASSES_swigconstant(_remcmd)
PRMPASSES = _remcmd.PRMPASSES

_remcmd.PRMSPASSINT_swigconstant(_remcmd)
PRMSPASSINT = _remcmd.PRMSPASSINT

_remcmd.PRMSPASSES_swigconstant(_remcmd)
PRMSPASSES = _remcmd.PRMSPASSES

_remcmd.PRMCURPASS_swigconstant(_remcmd)
PRMCURPASS = _remcmd.PRMCURPASS

_remcmd.PRMSPASSCTR_swigconstant(_remcmd)
PRMSPASSCTR = _remcmd.PRMSPASSCTR

_remcmd.PRMSPRING_swigconstant(_remcmd)
PRMSPRING = _remcmd.PRMSPRING

_remcmd.PRMFEEDDIR_swigconstant(_remcmd)
PRMFEEDDIR = _remcmd.PRMFEEDDIR

_remcmd.PRMFEEDLIMIT_swigconstant(_remcmd)
PRMFEEDLIMIT = _remcmd.PRMFEEDLIMIT

_remcmd.PRMTRNCTL_swigconstant(_remcmd)
PRMTRNCTL = _remcmd.PRMTRNCTL

_remcmd.PRMTAPERCTLF_swigconstant(_remcmd)
PRMTAPERCTLF = _remcmd.PRMTAPERCTLF

_remcmd.PRMTHREADCTL_swigconstant(_remcmd)
PRMTHREADCTL = _remcmd.PRMTHREADCTL

_remcmd.PRMZSTATE_swigconstant(_remcmd)
PRMZSTATE = _remcmd.PRMZSTATE

_remcmd.PRMXSTATE_swigconstant(_remcmd)
PRMXSTATE = _remcmd.PRMXSTATE

_remcmd.PRMTSTATE_swigconstant(_remcmd)
PRMTSTATE = _remcmd.PRMTSTATE

_remcmd.PRMFSTATE_swigconstant(_remcmd)
PRMFSTATE = _remcmd.PRMFSTATE

_remcmd.PRMDBGREG_swigconstant(_remcmd)
PRMDBGREG = _remcmd.PRMDBGREG

_remcmd.PRMZLIM_swigconstant(_remcmd)
PRMZLIM = _remcmd.PRMZLIM

_remcmd.PRMPSTATE_swigconstant(_remcmd)
PRMPSTATE = _remcmd.PRMPSTATE

_remcmd.SPIN_STEPS_swigconstant(_remcmd)
SPIN_STEPS = _remcmd.SPIN_STEPS

_remcmd.SPIN_MICRO_swigconstant(_remcmd)
SPIN_MICRO = _remcmd.SPIN_MICRO

_remcmd.SPIN_MIN_RPM_swigconstant(_remcmd)
SPIN_MIN_RPM = _remcmd.SPIN_MIN_RPM

_remcmd.SPIN_MAX_RPM_swigconstant(_remcmd)
SPIN_MAX_RPM = _remcmd.SPIN_MAX_RPM

_remcmd.SPIN_ACCEL_TIME_swigconstant(_remcmd)
SPIN_ACCEL_TIME = _remcmd.SPIN_ACCEL_TIME

_remcmd.Z_PITCH_swigconstant(_remcmd)
Z_PITCH = _remcmd.Z_PITCH

_remcmd.Z_RATIO_swigconstant(_remcmd)
Z_RATIO = _remcmd.Z_RATIO

_remcmd.Z_MICRO_swigconstant(_remcmd)
Z_MICRO = _remcmd.Z_MICRO

_remcmd.Z_MOTOR_swigconstant(_remcmd)
Z_MOTOR = _remcmd.Z_MOTOR

_remcmd.Z_ACCEL_swigconstant(_remcmd)
Z_ACCEL = _remcmd.Z_ACCEL

_remcmd.Z_BACKLASH_swigconstant(_remcmd)
Z_BACKLASH = _remcmd.Z_BACKLASH

_remcmd.X_PITCH_swigconstant(_remcmd)
X_PITCH = _remcmd.X_PITCH

_remcmd.X_RATIO_swigconstant(_remcmd)
X_RATIO = _remcmd.X_RATIO

_remcmd.X_MICRO_swigconstant(_remcmd)
X_MICRO = _remcmd.X_MICRO

_remcmd.X_MOTOR_swigconstant(_remcmd)
X_MOTOR = _remcmd.X_MOTOR

_remcmd.X_ACCEL_swigconstant(_remcmd)
X_ACCEL = _remcmd.X_ACCEL

_remcmd.X_BACKLASH_swigconstant(_remcmd)
X_BACKLASH = _remcmd.X_BACKLASH

_remcmd.Z_MOVE_MIN_swigconstant(_remcmd)
Z_MOVE_MIN = _remcmd.Z_MOVE_MIN

_remcmd.Z_MOVE_MAX_swigconstant(_remcmd)
Z_MOVE_MAX = _remcmd.Z_MOVE_MAX

_remcmd.Z_JOG_MIN_swigconstant(_remcmd)
Z_JOG_MIN = _remcmd.Z_JOG_MIN

_remcmd.Z_JOG_MAX_swigconstant(_remcmd)
Z_JOG_MAX = _remcmd.Z_JOG_MAX

_remcmd.X_MOVE_MIN_swigconstant(_remcmd)
X_MOVE_MIN = _remcmd.X_MOVE_MIN

_remcmd.X_MOVE_MAX_swigconstant(_remcmd)
X_MOVE_MAX = _remcmd.X_MOVE_MAX

_remcmd.X_JOG_MIN_swigconstant(_remcmd)
X_JOG_MIN = _remcmd.X_JOG_MIN

_remcmd.X_JOG_MAX_swigconstant(_remcmd)
X_JOG_MAX = _remcmd.X_JOG_MAX

_remcmd.TOTAL_PASSES_swigconstant(_remcmd)
TOTAL_PASSES = _remcmd.TOTAL_PASSES

_remcmd.SPRING_PASSES_swigconstant(_remcmd)
SPRING_PASSES = _remcmd.SPRING_PASSES

_remcmd.SPRING_PASS_INT_swigconstant(_remcmd)
SPRING_PASS_INT = _remcmd.SPRING_PASS_INT

_remcmd.CURRENT_PASS_swigconstant(_remcmd)
CURRENT_PASS = _remcmd.CURRENT_PASS

_remcmd.Z_MOVE_DIST_swigconstant(_remcmd)
Z_MOVE_DIST = _remcmd.Z_MOVE_DIST

_remcmd.Z_JOG_DIR_swigconstant(_remcmd)
Z_JOG_DIR = _remcmd.Z_JOG_DIR

_remcmd.Z_SET_LOC_swigconstant(_remcmd)
Z_SET_LOC = _remcmd.Z_SET_LOC

_remcmd.Z_LOC_swigconstant(_remcmd)
Z_LOC = _remcmd.Z_LOC

_remcmd.X_MOVE_DIST_swigconstant(_remcmd)
X_MOVE_DIST = _remcmd.X_MOVE_DIST

_remcmd.X_JOG_DIR_swigconstant(_remcmd)
X_JOG_DIR = _remcmd.X_JOG_DIR

_remcmd.X_SET_LOC_swigconstant(_remcmd)
X_SET_LOC = _remcmd.X_SET_LOC

_remcmd.X_LOC_swigconstant(_remcmd)
X_LOC = _remcmd.X_LOC

_remcmd.Z_START_LOC_swigconstant(_remcmd)
Z_START_LOC = _remcmd.Z_START_LOC

_remcmd.Z_END_LOC_swigconstant(_remcmd)
Z_END_LOC = _remcmd.Z_END_LOC

_remcmd.Z_RETRACT_swigconstant(_remcmd)
Z_RETRACT = _remcmd.Z_RETRACT

_remcmd.Z_FEED_PASS_swigconstant(_remcmd)
Z_FEED_PASS = _remcmd.Z_FEED_PASS

_remcmd.X_START_LOC_swigconstant(_remcmd)
X_START_LOC = _remcmd.X_START_LOC

_remcmd.X_END_LOC_swigconstant(_remcmd)
X_END_LOC = _remcmd.X_END_LOC

_remcmd.X_RETRACT_swigconstant(_remcmd)
X_RETRACT = _remcmd.X_RETRACT

_remcmd.X_FEED_PASS_swigconstant(_remcmd)
X_FEED_PASS = _remcmd.X_FEED_PASS

_remcmd.FEED_DIR_swigconstant(_remcmd)
FEED_DIR = _remcmd.FEED_DIR

_remcmd.FEED_TYPE_swigconstant(_remcmd)
FEED_TYPE = _remcmd.FEED_TYPE

_remcmd.FEED_swigconstant(_remcmd)
FEED = _remcmd.FEED

_remcmd.TAPER_Z_swigconstant(_remcmd)
TAPER_Z = _remcmd.TAPER_Z

_remcmd.TAPER_X_swigconstant(_remcmd)
TAPER_X = _remcmd.TAPER_X

_remcmd.TAPER_FLAG_swigconstant(_remcmd)
TAPER_FLAG = _remcmd.TAPER_FLAG

_remcmd.TURN_FLAG_swigconstant(_remcmd)
TURN_FLAG = _remcmd.TURN_FLAG

_remcmd.THREAD_DEPTH_swigconstant(_remcmd)
THREAD_DEPTH = _remcmd.THREAD_DEPTH

_remcmd.THREAD_LAST_FEED_swigconstant(_remcmd)
THREAD_LAST_FEED = _remcmd.THREAD_LAST_FEED

_remcmd.THREAD_H_FACTOR_swigconstant(_remcmd)
THREAD_H_FACTOR = _remcmd.THREAD_H_FACTOR

_remcmd.THREAD_ANGLE_swigconstant(_remcmd)
THREAD_ANGLE = _remcmd.THREAD_ANGLE

_remcmd.INDEX_PRE_SCALER_swigconstant(_remcmd)
INDEX_PRE_SCALER = _remcmd.INDEX_PRE_SCALER

_remcmd.INDEX_PERIOD_swigconstant(_remcmd)
INDEX_PERIOD = _remcmd.INDEX_PERIOD

_remcmd.MAX_PARM_swigconstant(_remcmd)
MAX_PARM = _remcmd.MAX_PARM

def remcmd():
    return _remcmd.remcmd()
remcmd = _remcmd.remcmd
# This file is compatible with both classic and new-style classes.
